[colors.primary]
background = "#141415"
foreground = "#cdcdcd"
dim_foreground = "#929292"
bright_foreground = "#dcdcdc"

[colors.cursor]
text = "#141415"
cursor = "#cdcdcd"

[colors.selection]
text = "#cdcdcd"
background = "#252530"

[colors.normal]
black = "#252530"
red = "#d8647e"
green = "#7fa563"
yellow = "#f3be7c"
blue = "#6e94b2"
magenta = "#bb9dbd"
cyan = "#aeaed1"
white = "#cdcdcd"

[colors.bright]
black = "#252530"
red = "#d8647e"
green = "#7fa563"
yellow = "#f3be7c"
blue = "#6e94b2"
magenta = "#bb9dbd"
cyan = "#aeaed1"
white = "#cdcdcd"

[colors.dim]
black = "#1f1f29"
red = "#b8556b"
green = "#6c8c54"
yellow = "#cfa269"
blue = "#5e7e97"
magenta = "#9f85a1"
cyan = "#9494b2"
white = "#aeaeae"

[[colors.indexed_colors]]
index = 16
color = "#e6917d"

[[colors.indexed_colors]]
index = 17
color = "#d399a6"

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"

[cursor.style]
shape = "Block"

[window]
dynamic_padding = true
title = "Terminal"

[window.padding]
x = 8
y = 8
