[colors.primary]
background = "#14171d"
foreground = "#c5c9c7"
dim_foreground = "#8c8e8d"
bright_foreground = "#d4d8d6"

[colors.cursor]
text = "#14171d"
cursor = "#c5c9c7"

[colors.selection]
text = "#c5c9c7"
background = "#22262d"

[colors.normal]
black = "#14171d"
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
blue = "#8ba4b0"
magenta = "#a292a3"
cyan = "#8ea4a2"
white = "#c8c093"

[colors.bright]
black = "#14171d"
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
blue = "#8ba4b0"
magenta = "#a292a3"
cyan = "#8ea4a2"
white = "#c8c093"

[colors.dim]
black = "#111419"
red = "#a7635e"
green = "#758369"
yellow = "#a79775"
blue = "#768b96"
magenta = "#8a7c8b"
cyan = "#798b8a"
white = "#aaa37d"

[[colors.indexed_colors]]
index = 16
color = "#c4937c"

[[colors.indexed_colors]]
index = 17
color = "#c69a81"

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"

[cursor.style]
shape = "Block"

[window]
dynamic_padding = true

[window.padding]
x = 8
y = 8
