[mgr]
show_hidden = true
ratio = [1, 2, 3]
linemode = "size"
sort_by = "natural"
[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', desc = "editor", block = true },
]
open = [
    { run = 'xdg-open "$1"', desc = "open", for = "linux" },
    { run = 'open "$@"', desc = "open", for = "macos" },
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
]
media = [
    { run = 'ffplay -loglevel quiet -noborder -infbuf -loop 0 "$@"', desc = "open image", for = "unix" }
]
[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "{image,audio,video}/*", use = "media" },
    { mime = "application/pdf", use = "open" },
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "open"] },
    { mime = "inode/empty", use = "edit" },
	{ mime = "*", use = [ "edit", "open" ] },
]
